version: "3.8"
services:
  postgres-db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: bdEva01
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 10

  app:
    container_name: eva01
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/bdEva01?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSl=false
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
    depends_on:
      postgres-db:
        condition: service_healthy
